# Generated by Django 5.1.1 on 2025-02-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0026_remove_salario_fecha_pago_alter_tarea_confirmacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='mensajewhatsapp',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='MensajeWhatsApp',
        ),
    ]
